project:
  type: website

website: 
  title: "Tidewater 2023 example"
  site-url: "https://tidewater2023.obrien.page"
  navbar: 
    left:
      - text: Abstract
        href: abstract/index.qmd
 
execute:
  freeze: auto