---
title: Cruise planning with reproducible analysis workflows
authors:
  - name: Michael HP O'Brien
    affiliations:
      - id: UMCES
        name: University of Maryland Center for Environmental Science
  - name: David H Secor
    affiliations:
      - ref: UMCES
---

*Reproducible research*; *literate programming*; *analysis workflows*: all catch phrases among data analysts -- but there's no reason why they should be confined to the analysis stage of a research project. Using a worked example in R, we outline a suite of reproducible workflows and show their applicability to field researchers.

Starting spring 2023, UMCES is embarking on an 8-year, multi-platform Before-After-Control-Impact monitoring program around the US Wind offshore wind development areas near Ocean City, MD (see [tailwinds.umces.edu](https://tailwinds.umces.edu) for project-specific information). To create reliable and reproducible cruise planning, we have developed an R-based workflow leveraging authoring within the [Quarto scientific publishing system](https://quarto.org/), communication utilizing [GitHub Pages](https://pages.github.com/), and analysis with the [*targets* package](https://docs.ropensci.org/targets/).

Quarto allows intuitive access to JavaScript libraries and website production within R, the *lingua franca* in fisheries analysis. This has lowered barriers to adoption by analysts and allowed for interactive data exploration by the multiple project PIs. That the information is easily hosted on a free website provided by GitHub Pages has sped communication with project funders and contracted fishers.

The *targets* package visualizes interrelated R code, allowing users to intuitively find where necessary changes to code must be made and only running what is necessary when those changes are made.

Structuring the workflow with *targets*, a program that maps R code dependencies and only runs what is needed, has increased clarity and efficiency of code by providing a visual touchstone of interrelated datasets.

Developing cruise plans in a literate programming framework has sped adoption by naive participants, future-proofed against loss of institutional knowledge, and increased awareness and participation by project funders.

All example materials are hosted in [GitHub repository](https://github.com/mhpob/tidewater-2023) and [resultant website](https://tidewater2023.obrien.page).


targets

qmd template

interactivity

transferability to website
